services:
  front:
    build: 
      context: ./rtb-front
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    command: ["npm", "run", "dev"]
  back:
    build:
      context: ./rtb-express
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    command: ["npm", "run", "start"]
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
     - mongo-compose-network
    # volumes:
    #   - ./mongo_volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rtb
networks:
  mongo-compose-network:
    driver: bridge